# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralVerticalLayout.setObjectName("centralVerticalLayout")
        self.controlsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.controlsHorizontalLayout.setObjectName("controlsHorizontalLayout")
        self.uploadPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadPushButton.setEnabled(False)
        self.uploadPushButton.setObjectName("uploadPushButton")
        self.controlsHorizontalLayout.addWidget(self.uploadPushButton)
        self.resetPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetPushButton.setEnabled(False)
        self.resetPushButton.setObjectName("resetPushButton")
        self.controlsHorizontalLayout.addWidget(self.resetPushButton)
        self.startPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startPushButton.setEnabled(False)
        self.startPushButton.setObjectName("startPushButton")
        self.controlsHorizontalLayout.addWidget(self.startPushButton)
        self.pausePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pausePushButton.setEnabled(False)
        self.pausePushButton.setCheckable(True)
        self.pausePushButton.setObjectName("pausePushButton")
        self.controlsHorizontalLayout.addWidget(self.pausePushButton)
        self.stopPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopPushButton.setEnabled(False)
        self.stopPushButton.setObjectName("stopPushButton")
        self.controlsHorizontalLayout.addWidget(self.stopPushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.controlsHorizontalLayout.addItem(spacerItem)
        self.clockLcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.clockLcdNumber.setEnabled(False)
        self.clockLcdNumber.setMinimumSize(QtCore.QSize(100, 0))
        self.clockLcdNumber.setNumDigits(8)
        self.clockLcdNumber.setObjectName("clockLcdNumber")
        self.controlsHorizontalLayout.addWidget(self.clockLcdNumber)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.controlsHorizontalLayout.addItem(spacerItem1)
        self.serialPortComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.serialPortComboBox.setObjectName("serialPortComboBox")
        self.controlsHorizontalLayout.addWidget(self.serialPortComboBox)
        self.connectPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectPushButton.setObjectName("connectPushButton")
        self.controlsHorizontalLayout.addWidget(self.connectPushButton)
        self.disconnectPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectPushButton.setEnabled(False)
        self.disconnectPushButton.setObjectName("disconnectPushButton")
        self.controlsHorizontalLayout.addWidget(self.disconnectPushButton)
        self.centralVerticalLayout.addLayout(self.controlsHorizontalLayout)
        self.devicesHorizontalLayout = QtWidgets.QHBoxLayout()
        self.devicesHorizontalLayout.setObjectName("devicesHorizontalLayout")
        self.tankGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.tankGroupBox.setObjectName("tankGroupBox")
        self.tankVerticalLayout = QtWidgets.QVBoxLayout(self.tankGroupBox)
        self.tankVerticalLayout.setObjectName("tankVerticalLayout")
        self.tankTableWidget = QtWidgets.QTableWidget(self.tankGroupBox)
        self.tankTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tankTableWidget.setObjectName("tankTableWidget")
        self.tankTableWidget.setColumnCount(4)
        self.tankTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tankTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tankTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tankTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tankTableWidget.setHorizontalHeaderItem(3, item)
        self.tankTableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tankVerticalLayout.addWidget(self.tankTableWidget)
        self.devicesHorizontalLayout.addWidget(self.tankGroupBox)
        self.turretGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.turretGroupBox.setObjectName("turretGroupBox")
        self.turretVerticalLayout = QtWidgets.QVBoxLayout(self.turretGroupBox)
        self.turretVerticalLayout.setObjectName("turretVerticalLayout")
        self.turretTableWidget = QtWidgets.QTableWidget(self.turretGroupBox)
        self.turretTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.turretTableWidget.setObjectName("turretTableWidget")
        self.turretTableWidget.setColumnCount(4)
        self.turretTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.turretTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.turretTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.turretTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.turretTableWidget.setHorizontalHeaderItem(3, item)
        self.turretTableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.turretVerticalLayout.addWidget(self.turretTableWidget)
        self.devicesHorizontalLayout.addWidget(self.turretGroupBox)
        self.targetGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.targetGroupBox.setObjectName("targetGroupBox")
        self.targetVerticalLayout = QtWidgets.QVBoxLayout(self.targetGroupBox)
        self.targetVerticalLayout.setObjectName("targetVerticalLayout")
        self.targetTableWidget = QtWidgets.QTableWidget(self.targetGroupBox)
        self.targetTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.targetTableWidget.setObjectName("targetTableWidget")
        self.targetTableWidget.setColumnCount(4)
        self.targetTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.targetTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.targetTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.targetTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.targetTableWidget.setHorizontalHeaderItem(3, item)
        self.targetTableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.targetVerticalLayout.addWidget(self.targetTableWidget)
        self.devicesHorizontalLayout.addWidget(self.targetGroupBox)
        self.centralVerticalLayout.addLayout(self.devicesHorizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Роботлон"))
        self.uploadPushButton.setText(_translate("MainWindow", "Загрузить настройки"))
        self.resetPushButton.setText(_translate("MainWindow", "Сброс"))
        self.startPushButton.setText(_translate("MainWindow", "Старт"))
        self.pausePushButton.setText(_translate("MainWindow", "Пауза"))
        self.stopPushButton.setText(_translate("MainWindow", "Стоп"))
        self.connectPushButton.setText(_translate("MainWindow", "Подключиться"))
        self.disconnectPushButton.setText(_translate("MainWindow", "Отключиться"))
        self.tankGroupBox.setTitle(_translate("MainWindow", "Танки"))
        item = self.tankTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Группа"))
        item = self.tankTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Статус"))
        item = self.tankTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Жизнь"))
        item = self.tankTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "В бою"))
        self.turretGroupBox.setTitle(_translate("MainWindow", "Турели"))
        item = self.turretTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Группа"))
        item = self.turretTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Статус"))
        item = self.turretTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Жизнь"))
        item = self.turretTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "В бою"))
        self.targetGroupBox.setTitle(_translate("MainWindow", "Мишени"))
        item = self.targetTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Группа"))
        item = self.targetTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Статус"))
        item = self.targetTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Жизнь"))
        item = self.targetTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "В бою"))

